import type { Metadata } from "next";
import Header from "./components/Header";
import { Libre_Baskerville } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Footer from "./components/Footer";
import Nav from "./components/Nav";

const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Courteous Curtis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-parchment dark:bg-blackboard ${libreBaskerville.className} bg-repeat bg-center text-[#111] dark:text-yellow-100 border-[#333] dark:border-yellow-100 border-4 m-2 min-h-screen transition-colors duration-150`}
      >
        <ThemeProvider attribute="class">
          <Header handleToggle={undefined} />
          <Nav isNav={undefined} />
          <div className="py-2 px-6">{children}</div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
